### PR TITLE
Build both an Intel and ARM Mac binary

### PR DESCRIPTION
**Pull request by ticky**
Requires Go 1.16beta1, and turning `GO111MODULE=off`, but there's no CI for this project right now!

### CODE REVIEW

**Comment by yob** [comment]
Tested like this:

```
$ docker run -v `pwd`:/work -w /work -it golang:1.16beta1 bash

root@de9c2f61c727:/work# GO111MODULE=off ./scripts/build 
Building yaml2json 💨

Download Dependency
Compiling for Intel macOS
👍  dist/yaml2json-darwin-amd64

Compiling for ARM macOS
👍  dist/yaml2json-darwin-arm64

Compiling for Linux
👍  dist/yaml2json-linux-amd64

All done! ✅
```

Seems to work!

I guess `GO111MODULE=off` is required because this repo hasn't been initialised as a module yet? I reckon it's worth prefixing the three `go build` calls in `script/build` with `GO111MODULE=off` so future us doesn't need to remember to include it.

**Comment by sj26** [comment]
> there's no CI for this project right now

Sounds like a good time to add it :-)

**Comment by ticky** [comment]
I'm not entirely certain what to use as a best practice template here, terminal-to-html has some custom tooling but I'm not clear on whether that's the best approach. Anyone got opinions?

**Comment by ticky** [comment]
Okay, this adds CI which will exercise building, however, we're deferring configuring a release process for another time. Ready for review!

**Review by sj26 — APPROVED** [review]
Very nice :+1:

```
$ ./scripts/build
Building yaml2json 💨

Download Dependency
go: downloading github.com/ghodss/yaml v1.0.0
go: downloading gopkg.in/yaml.v2 v2.4.0
Compiling for Intel macOS
👍  dist/yaml2json-darwin-amd64

Compiling for ARM macOS
👍  dist/yaml2json-darwin-arm64

Compiling for Linux
👍  dist/yaml2json-linux-amd64

All done! ✅

$ ./dist/yaml2json-darwin-amd64
yaml2json v0.1.0
Usage: yaml2json [file]

$ ./dist/yaml2json-darwin-amd64 <( echo "some: yaml" )
{"some":"yaml"}

$ ./dist/yaml2json-darwin-arm64
yaml2json v0.1.0
Usage: yaml2json [file]

$ ./dist/yaml2json-darwin-arm64 <( echo "some: yaml" )
{"some":"yaml"}
```

**Pull request merged**
